# Generated by Django 2.2.24 on 2021-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrageTache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleTache_text', models.CharField(max_length=120)),
                ('tempsMoyenTraitementH_dec', models.FloatField(default=0)),
                ('delaisJTolerance', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_text', models.CharField(default=' ', max_length=32)),
                ('prenom_text', models.CharField(max_length=32)),
                ('nom_text', models.CharField(max_length=32)),
                ('estActif_bool', models.BooleanField(default=True)),
                ('metier_text', models.CharField(max_length=50)),
                ('pourcentageAttribution_int', models.IntegerField(default=100)),
                ('adresseMail_text', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache_text', models.CharField(max_length=120)),
                ('creation_date', models.DateTimeField(verbose_name='Date de création')),
                ('jalon_date', models.DateTimeField(verbose_name='Date Jalon de réalisation')),
                ('commentaire_text', models.CharField(max_length=600)),
                ('priseEnChargePar_id', models.IntegerField(default=999999999)),
                ('creerPar_id', models.IntegerField(default=0)),
                ('urgence_bool', models.BooleanField(default=False)),
                ('codeTache_text', models.CharField(max_length=3)),
                ('etat_text', models.CharField(default='EC', max_length=2)),
            ],
        ),
    ]
