# Generated by Django 2.2.24 on 2021-08-28 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0002_personne_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
