# Generated by Django 3.0.8 on 2021-09-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0004_auto_20210830_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='metier_text',
            field=models.CharField(default='Non renseigné', max_length=50),
        ),
    ]
