# Generated by Django 3.0.8 on 2021-09-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0005_auto_20210901_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='creerPar_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HomeManager.Personne'),
        ),
    ]
