# Generated by Django 3.0.8 on 2021-09-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0006_tache_creerpar_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='creerPar_text',
        ),
    ]
