# Generated by Django 3.0.8 on 2021-10-23 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0007_remove_tache_creerpar_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='jalon_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), verbose_name='Date Jalon de réalisation'),
        ),
        migrations.CreateModel(
            name='Cryptos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('quantite', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeManager.Personne')),
            ],
        ),
    ]
