# Generated by Django 3.0.8 on 2021-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0008_auto_20211023_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypoCrypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('libelle', models.CharField(max_length=10)),
            ],
        ),
    ]
