# Generated by Django 3.0.8 on 2021-10-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0009_typocrypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptos',
            old_name='code',
            new_name='code_crypto',
        ),
        migrations.RenameField(
            model_name='cryptos',
            old_name='quantite',
            new_name='quantite_crypto',
        ),
    ]
