# Generated by Django 3.0.8 on 2021-10-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0010_auto_20211023_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptos',
            old_name='code_crypto',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='cryptos',
            old_name='quantite_crypto',
            new_name='quantite',
        ),
    ]
