# Generated by Django 3.0.8 on 2021-10-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0011_auto_20211023_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptos',
            options={'ordering': ['code']},
        ),
    ]
