# Generated by Django 3.0.8 on 2021-10-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0012_auto_20211023_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cryptos',
            new_name='Crypto',
        ),
    ]
