# Generated by Django 2.2.24 on 2021-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0015_auto_20211031_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='tchouCoinWallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='tchouCoin',
            field=models.FloatField(default=0),
        ),
    ]
