# Generated by Django 2.2.24 on 2021-10-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0016_auto_20211031_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='tchouCoin',
            field=models.FloatField(default=1),
        ),
    ]
