# Generated by Django 2.2.24 on 2021-11-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeManager', '0017_auto_20211031_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField(default=999)),
                ('libelleCourt', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('estActif_bool', models.BooleanField(default=True)),
            ],
        ),
    ]
